
package capa_presentacion;

import javax.swing.JOptionPane;
import capa_negocio.Data_Clientes;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class Formulario_Clientes extends javax.swing.JPanel {

    /**
     * Creates new form Formulario_Clientes
     */
    public Formulario_Clientes() {
        initComponents();
        ListarClientes();
    }
    
    private void ListarClientes() {
        DefaultTableModel tabla = new DefaultTableModel();
        Data_Clientes objEmp = new Data_Clientes();
        ArrayList<Data_Clientes> lista = objEmp.ListaClientes();

        tabla.addColumn("Id Cliente");
        tabla.addColumn("Nombre Completo");
        tabla.addColumn("Correo");
        tabla.addColumn("Telefono");

        tabla.setRowCount(lista.size());
        int i = 0;
        for (Data_Clientes emp : lista) {
            tabla.setValueAt(emp.getIdCliente(), i, 0);
            tabla.setValueAt(emp.getNombreCompleto(), i, 1);
            tabla.setValueAt(emp.getCorreo(), i, 2);
            tabla.setValueAt(emp.getTelefono(), i, 3);            
            i++;
        }
        this.jTable1.setModel(tabla);
    }
        
    public void LimpiarCajasTexto() {
        this.JtfidCliente.setText("");
        this.JtfnombreCompleto.setText("");
        this.Jtfcorreo.setText("");
        this.Jtftelefono.setText("");
    }      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBtEliminar = new javax.swing.JButton();
        JBtModificar = new javax.swing.JButton();
        JBtSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JtfnombreCompleto = new javax.swing.JTextField();
        Jblrol = new javax.swing.JLabel();
        JtfidCliente = new javax.swing.JTextField();
        Jblnombre = new javax.swing.JLabel();
        Jtfcorreo = new javax.swing.JTextField();
        JBtNuevo = new javax.swing.JButton();
        Jlbtitulo = new javax.swing.JLabel();
        JBtGuardar = new javax.swing.JButton();
        JblidCliente = new javax.swing.JLabel();
        Jtftelefono = new javax.swing.JTextField();
        Jbltelefono = new javax.swing.JLabel();

        JBtEliminar.setText("Eliminar:");
        JBtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtEliminarActionPerformed(evt);
            }
        });

        JBtModificar.setText("Modificar:");
        JBtModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtModificarActionPerformed(evt);
            }
        });

        JBtSalir.setText("Salir:");
        JBtSalir.setToolTipText("");
        JBtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtSalirActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        JtfnombreCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfnombreCompletoActionPerformed(evt);
            }
        });

        Jblrol.setText("Correo:");
        Jblrol.setToolTipText("");

        JtfidCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfidClienteActionPerformed(evt);
            }
        });

        Jblnombre.setText("Nombre:");

        Jtfcorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtfcorreoMousePressed(evt);
            }
        });
        Jtfcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfcorreoActionPerformed(evt);
            }
        });

        JBtNuevo.setText("Nuevo:");
        JBtNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtNuevoActionPerformed(evt);
            }
        });

        Jlbtitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Jlbtitulo.setText("Datos Clientes");

        JBtGuardar.setText("Guardar:");
        JBtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtGuardarActionPerformed(evt);
            }
        });

        JblidCliente.setText("Id:");

        Jtftelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtftelefonoMousePressed(evt);
            }
        });
        Jtftelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtftelefonoActionPerformed(evt);
            }
        });

        Jbltelefono.setText("Telefono:");
        Jbltelefono.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Jlbtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(JBtNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBtModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(JBtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Jbltelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Jtftelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Jblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(JblidCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JtfidCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(JtfnombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jblrol, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Jtfcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(JBtGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(JBtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Jlbtitulo)
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JtfidCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JblidCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JtfnombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jtfcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jblrol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jtftelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jbltelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JBtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtEliminarActionPerformed
        // TODO add your handling code here:
        try {
            JBtModificar.setEnabled(false);
            if (JtfidCliente.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingrese un ID para eliminar");
                return;
            }
            int confirm = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar?");
            if (confirm == 0) {
                Data_Clientes objEmp = new Data_Clientes();
                objEmp.setIdCliente(Integer.parseInt(JtfidCliente.getText()));
                JOptionPane.showMessageDialog(null, objEmp.EliminarCliente());
                ListarClientes();
                LimpiarCajasTexto();
                JtfidCliente.setEnabled(true);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar");
        }
    }//GEN-LAST:event_JBtEliminarActionPerformed
                                       
    private void JBtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtModificarActionPerformed
        // TODO add your handling code here:
        try {
            JBtModificar.setEnabled(false);
            Data_Clientes objEmp = new Data_Clientes();
            objEmp.setIdCliente(Integer.parseInt(this.JtfidCliente.getText()));
            objEmp.setNombreCompleto(this.JtfnombreCompleto.getText());
            objEmp.setCorreo(this.Jtfcorreo.getText());
            objEmp.setTelefono(this.Jtftelefono.getText());
            JOptionPane.showMessageDialog(null, objEmp.EditarCliente());
            ListarClientes();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al modificar");
        }
    }//GEN-LAST:event_JBtModificarActionPerformed

    private void JBtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtSalirActionPerformed
        // TODO add your handling code here:
        int r = JOptionPane.showConfirmDialog(null, "¿Está seguro?");
        if (r == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_JBtSalirActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        JtfidCliente.setEnabled(false);
        JBtModificar.setEnabled(true);
        int rec = this.jTable1.getSelectedRow();
        this.JtfidCliente.setText(jTable1.getValueAt(rec, 0).toString());
        this.JtfnombreCompleto.setText(jTable1.getValueAt(rec, 1).toString());
        this.Jtfcorreo.setText(jTable1.getValueAt(rec, 2).toString());
        this.Jtftelefono.setText(jTable1.getValueAt(rec, 3).toString());
    }//GEN-LAST:event_jTable1MousePressed

    private void JtfnombreCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfnombreCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfnombreCompletoActionPerformed

    private void JtfidClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfidClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfidClienteActionPerformed

    private void JtfcorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtfcorreoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfcorreoMousePressed

    private void JtfcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfcorreoActionPerformed

    private void JBtNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtNuevoActionPerformed
        // TODO add your handling code here:
        JBtModificar.setEnabled(false);
        JtfidCliente.setEnabled(true);
        JBtGuardar.setEnabled(true);
        LimpiarCajasTexto();
        ListarClientes();
    }//GEN-LAST:event_JBtNuevoActionPerformed

    private void JBtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtGuardarActionPerformed
        // TODO add your handling code here:
        try {
            JBtModificar.setEnabled(false);
            if (JtfidCliente.getText().isEmpty() || JtfnombreCompleto.getText().isEmpty() || Jtfcorreo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingrese todos los campos");
                return;
            }
            Data_Clientes objEmp = new Data_Clientes();
            objEmp.setIdCliente(Integer.parseInt(this.JtfidCliente.getText()));
            objEmp.setNombreCompleto(this.JtfnombreCompleto.getText());
            objEmp.setCorreo(this.Jtfcorreo.getText());
            objEmp.setTelefono(this.Jtftelefono.getText());
            JOptionPane.showMessageDialog(null, objEmp.GuardarCliente());
            ListarClientes();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar");
        }
    }//GEN-LAST:event_JBtGuardarActionPerformed

    private void JtftelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtftelefonoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtftelefonoMousePressed

    private void JtftelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtftelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtftelefonoActionPerformed

    public static void main(String[] args) {
        JFrame frame = new JFrame("Formulario Clientes"); // Crea una ventana con el título "Formulario Clientes"
        Formulario_Clientes panel = new Formulario_Clientes(); // Crea una instancia del panel Formulario_Clientes
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Cierra la aplicación al presionar la "X"
        frame.setSize(1100, 500); //  tamaño de la ventana a 1100x500 
        frame.setContentPane(panel); // Agrega el panel Formulario_Clientes a la ventana
        frame.setVisible(true); // Muestra la ventana en pantalla
        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtEliminar;
    private javax.swing.JButton JBtGuardar;
    private javax.swing.JButton JBtModificar;
    private javax.swing.JButton JBtNuevo;
    private javax.swing.JButton JBtSalir;
    private javax.swing.JLabel JblidCliente;
    private javax.swing.JLabel Jblnombre;
    private javax.swing.JLabel Jblrol;
    private javax.swing.JLabel Jbltelefono;
    private javax.swing.JLabel Jlbtitulo;
    private javax.swing.JTextField Jtfcorreo;
    private javax.swing.JTextField JtfidCliente;
    private javax.swing.JTextField JtfnombreCompleto;
    private javax.swing.JTextField Jtftelefono;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
